### 第一步：模拟登陆，返回token
GET http://localhost:9009/login


### 第二步：请求带上token，请求/user端点
GET http://localhost:9009/user

### 第三步：请求带上token，请求/admin
GET http://localhost:9009/admin
Authorization:Bearer 第一步产生的token
###
